apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app-deployment
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/seif982/CloudDevOpsProject.git'  
    targetRevision: HEAD
    path: FinalProject/k8s
  destination:
    server: 'https://kubernetes.default.svc'  
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
